# -*- coding: utf-8 -*-
"""Bài tập lớn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UGG0U_Hs5X3HSijvZ04EbRz3j7nrcj5Z
"""

# Tính giai thừa của một số n

n = int(input("Nhập số n: "))

giai_thua = 1

if n < 0:
    print("Không có giai thừa cho số âm")
elif n == 0:
    print("0! = 1")
else:
    for i in range(1, n + 1):
        giai_thua *= i

    print(f"{n}! = {giai_thua}")

# Tính trung bình cộng của dãy số

day_so = [2, 4, 6, 8, 10]

tong = sum(day_so)
so_luong = len(day_so)

trung_binh = tong / so_luong

print("Giá trị trung bình:", trung_binh)

# Tính số tiền sau 12 tháng

so_tien_ban_dau = float(input("Nhập số tiền ban đầu: "))
lai_suat = float(input("Nhập lãi suất hàng tháng (%): "))

# Đổi % sang số thập phân
r = lai_suat / 100

so_tien_sau_12_thang = so_tien_ban_dau * (1 + r) ** 12

loi_nhuan = so_tien_sau_12_thang - so_tien_ban_dau

print("Số tiền sau 12 tháng:", round(so_tien_sau_12_thang, 2))
print("Lợi nhuận:", round(loi_nhuan, 2))
